version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9

    working_directory: /Github

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: Run Tests
          command: |
                 .venv/bin/activate
                 flake8 –-exclude=venv* --statistics
                 pytest –-junitxml=test-results/junit.xml
      - store_test_results:
             path: test-results
      - store_artifacts:
              path: test-result
