version: 2.1

jobs:
  build:
    docker:
      - image: python:3.9

    working_directory: /To-Do-List-App

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt

      # Run tests
      - run:
          name: Run Tests
          command: |
            pytest

      # Deploy to deployment directory
      - run:
          name: Deploy to DEPLOY-{CURRENT_DATE}
          command: |
            mkdir -p DEPLOY-$(date +"%Y-%m-%d")
            cp -r . DEPLOY-$(date +"%Y-%m-%d")

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main

