version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9

    working_directory: /app

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt

      - run:
          name: Run Tests
          command: |
            python manage.py test

      - persist_to_workspace:
          root: /app
          paths:
            - .

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
